"""Seeded scenario world generation.

Constitution Principle VI, Phase 2: the simulator exists so the mechanism
can be exercised before any transport or storage is wired in. Every random
choice flows from an explicitly passed ``random.Random(seed)`` (D-009) —
never the module-level global — so a scenario is fully reproducible.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from stakeroute.simulator.agents import (
    HONEST_PROFILES,
    AgentProfile,
    forecast_probability,
)

NOISE_SOURCES = ("logs", "metrics", "deploys", "security", "payments")
BASE_TIMESTAMP_MS = 1_756_449_000_000


@dataclass(frozen=True, slots=True)
class SignalSpec:
    """A background noise signal — carries no diagnostic weight of its own."""

    source: str
    source_event_id: str
    observed_at_ms: int
    payload: dict


@dataclass(frozen=True, slots=True)
class HypothesisSpec:
    """A hypothesis as generated by the scenario, including its ground truth."""

    id: str
    statement: str
    prior_probability: float
    impact_minor_units: int
    urgency: float
    review_cost: float
    deadline_ms: int
    created_at_ms: int
    ground_truth: int  # 1 = true, 0 = false


@dataclass(frozen=True, slots=True)
class ForecastSpec:
    """A generated agent forecast, ready to be submitted through ingestion."""

    hypothesis_id: str
    agent_id: str
    probability: float
    stake: int
    evidence_cluster_id: str
    source_event_id: str


@dataclass(frozen=True, slots=True)
class ScenarioWorld:
    """The complete output of one seeded scenario generation."""

    seed: int
    signals: tuple[SignalSpec, ...]
    hypotheses: tuple[HypothesisSpec, ...]
    agents: tuple[AgentProfile, ...]
    forecasts: tuple[ForecastSpec, ...]


def generate_world(
    seed: int, rng: random.Random | None = None, noise_count: int = 500
) -> ScenarioWorld:
    """Generate the baseline demonstration scenario for a given seed.

    Produces ``noise_count`` background noise signals, one genuine payment
    incident, one plausible-but-wrong database hypothesis, and forecasts
    from the six honest agent profiles on both hypotheses.
    """
    active_rng = rng if rng is not None else random.Random(seed)

    signals = tuple(
        SignalSpec(
            source=(source := active_rng.choice(NOISE_SOURCES)),
            source_event_id=f"noise-{i}",
            observed_at_ms=BASE_TIMESTAMP_MS + i * 37,
            payload={
                "metric": f"{source}_signal",
                "value": round(active_rng.uniform(0.0, 1.0), 3),
            },
        )
        for i in range(noise_count)
    )

    payment_hypothesis = HypothesisSpec(
        id="h-payment-failure",
        statement="payment_gateway_failure",
        prior_probability=0.30,
        impact_minor_units=800_000_000,
        urgency=1.0,
        review_cost=1.0,
        deadline_ms=BASE_TIMESTAMP_MS + 3_600_000,
        created_at_ms=BASE_TIMESTAMP_MS,
        ground_truth=1,
    )
    database_hypothesis = HypothesisSpec(
        id="h-database-saturation",
        statement="database_saturation",
        prior_probability=0.30,
        impact_minor_units=150_000_000,
        urgency=0.8,
        review_cost=1.0,
        deadline_ms=BASE_TIMESTAMP_MS + 3_600_000,
        created_at_ms=BASE_TIMESTAMP_MS,
        ground_truth=0,
    )
    hypotheses = (payment_hypothesis, database_hypothesis)

    forecasts = []
    for profile in HONEST_PROFILES:
        for hypothesis in hypotheses:
            ground_truth = bool(hypothesis.ground_truth)
            probability = forecast_probability(active_rng, ground_truth, profile)
            stake = active_rng.randint(10, 40)
            forecasts.append(
                ForecastSpec(
                    hypothesis_id=hypothesis.id,
                    agent_id=profile.agent_id,
                    probability=probability,
                    stake=stake,
                    evidence_cluster_id=f"{profile.agent_id}-{hypothesis.id}-evidence",
                    source_event_id=f"{profile.agent_id}-{hypothesis.id}-forecast",
                )
            )

    return ScenarioWorld(
        seed=seed,
        signals=signals,
        hypotheses=hypotheses,
        agents=HONEST_PROFILES,
        forecasts=tuple(forecasts),
    )
